---

---

<link rel="stylesheet" href="styles.css" type="text/css">

#### **Working papers**

[Why Has Participatory Budgeting Adoption Declined in Brazil?](https://www.oidp.net/docs/repo/doc639.pdf){target="_blank"}

[Métodos Quantitativos e Qualitativos: uma proposta de integração](https://www.abcp2020.sinteseeventos.com.br/arquivo/downloadpublic?q=YToyOntzOjY6InBhcmFtcyI7czozNToiYToxOntzOjEwOiJJRF9BUlFVSVZPIjtzOjQ6IjMxNzUiO30iO3M6MToiaCI7czozMjoiZTIxYzJjNzUwZDA1MjI3NDc1NzM4ZmY5NGY1ZDgzNmEiO30%3D){target="_blank"}

<p>&nbsp;</p>

#### **Publicações revisadas pelos pares**

2017 - [O debate sobre o federalismo e suas implicações para a governabilidade no Brasil (1988-2015)](https://anpocs.com/index.php/bib-pt/bib-83/11094-o-debate-sobre-o-federalismo-e-suas-implicacoes-para-a-governabilidade-no-brasil/file){target="_blank"}. Revista Brasileira de Informação Bibliométrica em Ciências Sociais (BIB) 83(1), 69-92.

2015 - [O nó da reforma tributária no Brasil (1995-2008)](https://doi.org/10.17666/308993-113/2015){target="_blank"}. Revista Brasileira de Ciências Sociais, 30(89), 93-113.

<p>&nbsp;</p>

#### **Apresentaçoes em Congressos**

2020 - [Métodos Quantitativos e Qualitativos: uma proposta de integração](https://www.abcp2020.sinteseeventos.com.br/arquivo/downloadpublic?q=YToyOntzOjY6InBhcmFtcyI7czozNToiYToxOntzOjEwOiJJRF9BUlFVSVZPIjtzOjQ6IjMxNzUiO30iO3M6MToiaCI7czozMjoiZTIxYzJjNzUwZDA1MjI3NDc1NzM4ZmY5NGY1ZDgzNmEiO30%3D){target="_blank"}. ANPOCS (2020) e ABCP (2020)

2018 - [Why Has Participatory Budgeting Adoption Declined in Brazil?](https://www.oidp.net/docs/repo/doc639.pdf){target="_blank"}. American Political Science Assosiation. Boston, Massachusetts (2020), ABCP (2018).

2015 - [Efficiency Measurement of Local Public Sector in International Perspective: a literature survey](https://www.ippapublicpolicy.org/file/paper/1435111240.pdf){target="_blank"}. International Conference on Public Policy, Milan.

2015 - [Desafios da centralização das compras públicas: o caso das passagens aéreas do Estado de São Paulo](https://github.com/Murilojunqueira/Murilojunqueira.github.io/raw/main/files/silo.tips_desafios-da-centralizaao-das-compras.pdf){target="_blank"} (com Daniel Araujo e Jorge Oliveira Silva). VIII Congresso Consad de Gestão Pública	2015

<p>&nbsp;</p>


#### **Teses e Dissertações**

2017 - [Instituições fiscais e eficiência governamental: um estudo de caso sobre a saúde pública municipal no Estado de São Paulo](https://teses.usp.br/teses/disponiveis/8/8131/tde-15022018-120151/pt-br.php){target="_blank"}. Tese de Doutorado defendida pelo Departamento de Ciência Política da Universidade de São Paulo.  

2011 - [O nó tributário: por que não se aprova uma reforma tributária no Brasil](https://www.teses.usp.br/teses/disponiveis/8/8131/tde-05072011-131136/en.php){target="_blank"}. Dissertação de mestrado defendida no Departamento de Ciência Política da Universidade de São Paulo.  

2009 - [IDESP, bônus e acompanhamento das escolas com pior desempenho.](https://github.com/Murilojunqueira/Murilojunqueira.github.io/raw/main/files/Relat%C3%B3rio%20de%20apresenta%C3%A7%C3%A3o_%20IDESP%2C%20b%C3%B4nus%20e%20acompanhamento%20das%20escolas%20com%20pior%20desempenho..pdf){target="_blank"} Relatório de conclusão do curso de formação dos Especialistas em Políticas Públicas do Estado de São Paulo, na FUNDAP-SP




